#
# wrong memory access
#

.PHONY: all
all:
	@echo "**** see Makefile for relevant build targets ****"

build_stuff: hello_world.c

.PHONY: clean
clean:
	rm -f *~
	rm -f hello_world

distclean: clean
