#
# some stuff around time topics
#


.PHONY: all
all:
	@echo "**** see Makefile for relevant build targets ****"

build_stuff: hello_time.c
	gcc -Wall -Wextra -o hello_time hello_time.c

.PHONY: clean
clean:
	rm -f *~
	rm -f hello_time

distclean: clean
