#
# some stuff around ttenv topics
#


.PHONY: all
all:
	@echo "**** see Makefile for relevant build targets ****"

build_stuff: hello_ttenv.c
	gcc -Wall -Wextra -o hello_ttenv hello_ttenv.c

.PHONY: clean
clean:
	rm -f *~
	rm -f .*~
	rm -f hello_ttenv

distclean: clean
